name: Build APK

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:    
  build:
    name: Flutter app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603
      - name: Flutter action
        uses: subosito/flutter-action@v2.6.1
        with:
          channel: master
      - run: flutter pub get -v
      - run: flutter test
      - run: flutter build apk
      
      
      
      
