name: Deploy to web
on:
  # Enable manual run
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy web build"
        required: true
        default: "staging"
        type: choice
        options:
          - staging
          - prod

# Declare default permissions as read only.
permissions: read-all

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Set up Flutter.
      - name: Clone Flutter repository with master channel
        uses: subosito/flutter-action@6c2e035f2692eeac890d854df95630c72673f130
        with:
          channel: master
      - run: flutter doctor -v

      - name: Install web dependencies
        uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e
      - run: npm install

      # Checkout gallery code and get packages.
      - name: Checkout code
        uses: actions/checkout@d171c3b028d844f2bf14e9fdec0c58114451e4bf
      - run: flutter pub get
      
      # Run tests
      - run: flutter test
      
      # Build web
      - run: flutter build -v web --release
      
      
